@extends('templates.form')
@section('title','U-farm | 退会ページ')
@section('href','user_delete.css')

@section('header')
    @component('components.header')
        @slot('link')
            /
        @endslot
        @slot('title')
            Top
        @endslot
        @slot('link2')
            /item
        @endslot
        @slot('title2')
            Items
        @endslot
        @slot('link3')
            /setting_second
        @endslot
        @slot('title3')
            Setting
        @endslot
        @slot('link4')
            /logout
        @endslot
        @slot('title4')
            logout
        @endslot
    @endcomponent
@endsection

@section('form')
    <form action="/admin/{{ $admin->id }}" method="POST">
        @csrf
        @method('DELETE')
        <input type="submit" value="退会する">
    </form>
@endsection

@section('footer')
    @component('components.footer')
        @slot('link')
            /
        @endslot
        @slot('title')
            Top
        @endslot
        @slot('link2')
            /item
        @endslot
        @slot('title2')
            Items
        @endslot
        @slot('link3')
            /setting_second
        @endslot
        @slot('title3')
            Setting
        @endslot
        @slot('link4')
            /logout
        @endslot
        @slot('title4')
            logout
        @endslot
    @endcomponent
@endsection
