version: "3"
services:
  app:
    build:
      context: ./docker/php
      args:
        - TZ=${TZ}
    volumes:
      - ./server:/work
      - ./.env:/work/.env
      - ./logs:/var/log/php
      - ./docker/php/php.ini:/usr/local/etc/php/php.ini
    working_dir: /work
    environment:
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
      - PUID=${WORKSPACE_PUID}
      - PGID=${WORKSPACE_PGID}

  web:
    image: nginx:1.17-alpine
    depends_on:
      - app
    ports:
      - 8080:80
    volumes:
      - ./server:/work
      - ./logs:/var/log/nginx
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    environment:
      - TZ=${TZ}

  db:
    image: mysql:8.0
    volumes:
      - database:/var/lib/mysql
      - ./logs:/var/log/mysql
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USERNAME}
      - MYSQL_PASSWORD=${DB_PASSWORD}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - TZ=${TZ}
  
  nodejs:
    restart: "no"
    image: node:10.16
    volumes:
      - ./:/var/nodeapp/
    working_dir: /var/nodeapp/
    tty: true
    ports:
      - 3000:3000
    environment:
      - TZ=UTC
      - PUID=${WORKSPACE_PUID}
      - PGID=${WORKSPACE_PGID}
      - HOST=0.0.0.0

volumes:
  database:
